[target.riscv32imac-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [ "--cfg",  "espidf_time64"]

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = "v5.3.3"

[alias]
b-c6 = "build --target riscv32imac-esp-espidf --config env.MCU=\"esp32c6\""
b-s3 = "build --target xtensa-esp32s3-espidf --config env.MCU=\"esp32s3\""
