name: CI & Release

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Firmware and Apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            web/package-lock.json

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: uv sync
        run: uv sync

      - name: Setup standard Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown,x86_64-pc-windows-gnu,x86_64-unknown-linux-musl,aarch64-unknown-linux-musl,arm-unknown-linux-musleabi,aarch64-apple-darwin

      - name: Install espup
        run: |
          curl -L https://github.com/esp-rs/espup/releases/latest/download/espup-x86_64-unknown-linux-gnu -o espup
          chmod +x espup
          ./espup install

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install espflash and wasm-bindgen
        run: cargo binstall -y espflash wasm-bindgen-cli@0.2.127

      - name: Enable caching
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-esp-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        run: |
          source ~/export-esp.sh
          cargo fmt --all -- --check --color always

      - name: Run Clippy (C6 Target)
        run: |
          source ~/export-esp.sh
          cargo clippy -p ossm-esp32 --config='unstable.build-std=["core","alloc"]' --target riscv32imac-unknown-none-elf --features esp32c6 --no-default-features -- -D warnings

      - name: Run release script
        run: |
          source ~/export-esp.sh
          uv run scripts/release.py

      - name: Prepare ELF files and Zip
        run: |
          cp target/riscv32imac-unknown-none-elf/release/ossm-rust release/ossm-esp32c6.elf
          cp target/xtensa-esp32s3-none-elf/release/ossm-rust release/ossm-esp32s3.elf
          cd release
          zip -r ../ossm-release.zip *

      - name: Upload Release Zip
        uses: actions/upload-artifact@v4
        with:
          name: ossm-release
          path: ossm-release.zip
